### ISSUE TITLE
Slightly different result

### ISSUE THREAD

**Issue by AndrewSchork** [pappewaio/vcf_reference_build_tools#3]
It would be great if the output was slightly different.

The goal is to provide updated SNP IDs for all variants within a specific VCF file.  The key information within a VCF is the CHR POS REF and ALT columns.  Let's just copy the header columns and add the new columns after, so it's straightforward.

What I would love is for the pipeline to return the five original columns from the VCF, supplemented with GRCH 38 CHR and POS and dbSNP151 rsIDs.

So, If the original VCF file contained this information

CHR POS ID REF ALT
9 917085 . C T 
9 17101 rs369153088 G A
9 20724 . G C
9 32566rs113861604 C A
9 38962 rs367841173 G A
9 39037 . A C

The return file would look like:

CHR POS ID REF ALT CHROM_GRCh38 POS_GRCh38 ID_dbSNP151
9 917085 . C T 18085 rs199659819
9 17101 rs369153088 G A 18101 rs369153088
9 20724 . G C 21724 rs1234567
9 32566rs113861604 C A 32566 rs113861604
9 38962 rs367841173 G A 39962 rs367841173
9 39037 . A C 40037 chr9_39037_A_C

Where the first 5 columns are just identical in order and content to the VCF and the last 3 are the new information.  We should return a SNP ID if the CHR POS REF and ALT match and entry in dbSNP, otherwise we should give a string that fills in CHR_POS_REF_ALT as a unique ID, where the POS is in the same format as the original file. (Note: perhaps we need two IDs? one for each build where the POS/CHR is either original or 38?)

**Comment by pappewaio** [comment]
This is straight forward to do. But two small things we need to make a decision on first:
- As you say, giving an rsid the chr_pos_a1_a2 identifier makes sense to be for both genome builds.
- Also for a1 and a2 where we can lift information from either the source GRCh37 or from GRCh38, or both.

But I wonder if it actually is useful to have a placeholder rsid where it is missing. If someone need to make that, then it is easily accessible from this map file using a simple AWK command. Or what do you think?

**Comment by AndrewSchork** [comment]
In the naming, I think REF and ALT and POS should come from the source, as a default.  

If we want to provide a second column - one that gives the placeholder ID of "CHR_POS_REF_ALT" - in terms of GRCh38 - I guess in makes sense to make the REF-ALT from GRCh38 also.  Although this is application (the second name column) does not _currently_ have a use case.

The main task here is to give the iPSYCH data updated SNP IDs within those files, not necessarily solve all general purpose naming problems.   So getting the hg19 naming all internally consistent (within the source file - here the iPSYCH VCFs) is the priority.  I think for hg38 information, it has be to seen as a kind of "beta" until someone comes with a particular use case that we can train it on.

**Comment by AndrewSchork** [comment]
In other words, the main tasks here are:
1) copy from the source file the CHR, POS, REF, ALT
2) Look those up in dbsnp and return an rsid
3) if no rsid, copy CHR_POS_REF_ALT in place
4) (beta) provide an hg38 position
5) (beta) provide an hg38 CHR_POS_REF_ALT name where all data is in terms of hg38

**Comment by vaqm2** [comment]
I think this could be done with a simple script that uses the tabix and liftover modules. I know there's a tabix library for both perl and python. I might have to check if there is one for liftover. Otherwise you can also call the liftover binary as a system command from within the code.

A usage scenario could be like `query_snp.pl/py --chr 1 --pos 1000 --ref A --alt G` depending on your flavor of perl or python.

**Comment by pappewaio** [comment]
> I think this could be done with a simple script that uses the tabix and liftover modules. I know there's a tabix library for both perl and python. I might have to check if there is one for liftover. Otherwise you can also call the liftover binary as a system command from within the code.
> 
> A usage scenario could be like `query_snp.pl/py --chr 1 --pos 1000 --ref A --alt G` depending on your flavor of perl or python.

What is happening right now is that all dbsnp SNPs (no indels) in GRCh38 have been lifted over to GRCh37 in a map file that I use in cleansumstats. In theory, one would assume we could provide an rsid for most SNPs in the imputed data as there are around 500 million SNPs in the dbsnp reference. But for some reason we did not get 100% hits. If I guess, the reason could be: 
- Failed liftover (no map between 38 and 37 for these positions)
- Duplicated entries, can happen when a position in 37 or 38 has two or more coordinates in the other.
The reference I use for cleansumstats can in that way be seen as curated, as we don't allow these uncertain positions.

But I will re-run using an updated version of the code according to Andrews suggestions and then investigate SNP by SNP why they lack map information in my dbsnp reference file.

**Comment by AndrewSchork** [comment]
What is the % of non-hits?

**Comment by pappewaio** [comment]
As of commit 388fc491a7025455bdb721331973ea2a28eeb9eb, the output now looks like this for the included example data.
```
ROWINDEX  CHR  POS        ID  REF  ALT  CHROM_GRCh38  POS_GRCh38  ID_dbSNP151  REF_dbSNP151  ALT_dbSNP151
42        10   100157763  .   C    T    NA            NA          NA           NA            NA
43        10   101966771  .   T    C    NA            NA          NA           NA            NA
44        10   102814179  .   T    C    10            104573936   rs284858     T             C
45        10   104355789  .   T    C    NA            NA          NA           NA            NA
46        10   10574522   .   T    C    10            10616485    rs2025468    T             C
47        10   105905360  .   A    G    NA            NA          NA           NA            NA
48        10   106322887  .   C    T    NA            NA          NA           NA            NA
49        10   106371703  .   C    A    10            108131461   rs1409409    C             A
50        10   106524737  .   G    A    NA            NA          NA           NA            NA
```
Because the resulting files are relatively small, I thought it was worth keeping the dbSNP ref and alt as well. They can be interesting to study, when diagnosing the result.

Next step is to write a small diagnosis suite to analyse how much that match, and what is NA.

**Comment by AndrewSchork** [comment]
I would be curious about:

How many "." in original?
How many "."  in original get NA in ID_dbSNP151?
How many "."  in original get rsID in ID_dbSNP151?
How many rsID in original get NA in ID_dbSNP151?
How many rsID change to a new rsID?

**Comment by pappewaio** [comment]
> How many rsID change to a new rsID?

I had just finished the diagnosis tool and uploaded to GDK, but I missed this critical piece, so I will include it as well and upload again

**Comment by pappewaio** [comment]
After running the code on chr22, which took 1h 30m, we got this result:
```
Both_RSIS_exists           442224
only_dbSNP_RSID_exists     72624
only_input_RSID_exists     2254
No_RSID_exists             7464
Both_RSID_exists_and_same  441721
Both_RSID_exists_not_same  503
Total_rows_excl_header     524566
```

**Comment by pappewaio** [comment]
I closed this issue. We can start a new one if we want to take the discussion further.
