### ISSUE TITLE
Create functionality for replacing the ID in a vcf

### ISSUE THREAD

**Issue by pappewaio** [pappewaio/vcf_reference_build_tools#6]
To make the update easy, but also possible to locally test that things work as expected.

**Comment by AndrewSchork** [comment]
I believe this is a one liner with VCF tools - probably not necessary to reinvent the wheel?

**Comment by pappewaio** [comment]
I think so too, but I will make a wrapper and make sure to document how to get a conda environment to have easy access. Just to have everything in a form to easy re-run

**Comment by pappewaio** [comment]
PR #9
